// <auto-generated />
using System;
using FilPan.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilPan.Migrations.Migrations
{
    [DbContext(typeof(FilPanDbContext))]
    [Migration("20200927115333_AddFileMd5s")]
    partial class AddFileMd5s
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("FilPan.Entities.FileCid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<string>("Cid")
                        .HasColumnName("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(512);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnName("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnName("updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dt_file_cid");
                });

            modelBuilder.Entity("FilPan.Entities.FileMd5", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKey")
                        .HasColumnName("data_key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("dt_file_md5");
                });

            modelBuilder.Entity("FilPan.Entities.FileName", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("dt_file_name");
                });

            modelBuilder.Entity("FilPan.Entities.UploadLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<string>("AlipayFileKey")
                        .HasColumnName("alipay_file_key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKey")
                        .HasColumnName("data_key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .HasColumnName("hashed_password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("WxpayFileKey")
                        .HasColumnName("wxpay_file_key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("dt_upload_log");
                });
#pragma warning restore 612, 618
        }
    }
}
